version: '3.8'

services:
    hevy-dashboard-app:
      build: .
      ports:
        - "80:80"
      restart: always
      container_name: hevy-dashboard-web
      environment:
        - FLUTTER_ENV=production